### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by orasunis** [Cydhra/Vibrant#3]
To have a working command system we need to implement more.
We currently have a working PacketEvent, but no e.g. VibrantMessagePacket
this needs to be implemented soon.
To allow client-side responses to various commands, an api to minecrafts GuiNewChat class should be implemented as well.
For easier implementations of Output we need a method in the VibrantFactory to create VibrantChatStyle.

**Comment by Flaflo** [comment]
I dont think its a good idea to execute commands through chat messages

**Comment by Cydhra** [comment]
Ah I will reopen that, because although we do it in a dedicated GUI, we might need more stuff hooked.
