### ISSUE TITLE
[Bug] AccountLogin session

### ISSUE THREAD

**Issue by QumaDEVSKIDHD** [Cydhra/Vibrant#6]
Hab mich versucht mit nem Alt einzuloggen, kein Error, habe den auch in der SinglePlayer Welt, aber wenn auch beispielsweise auf poke.sexy gehe bekomme ich ne NullPointerException.

**Comment by Cydhra** [comment]
Der Account Login ist ziemlich problematisch, eventuell liegt es an der Authentication-Library. Da muss einiges getan werden.

**Comment by Cydhra** [comment]
Fixed. Der Manager ist zwar immernoch eine Baustelle, aber der Direct Login funktioniert (zumindest meistens)

**Comment by QumaDEVSKIDHD** [comment]
Bei mir immer noch nicht. Außerdem fehlt n Try-Catch (Client crashed bei ner InvalidCredentialsException)

**Comment by QumaDEVSKIDHD** [comment]
Man wird ja in den User eingeloggt, aber man bekommt trotzdem ne NullPointerException beim joinen eines Servers.

**Comment by Cydhra** [comment]
Nicht reproduzierbar, ich brauche mehr Informationen. Vorgehensweise, Logs, Fehlermeldungen, Crashlogs etc.
